version: "3.9"

services:
    php:
        container_name: php
        image: php
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "80:80"
        depends_on:
            - postgresql
        environment:
            PGUSER: postgres
            PGPASSWORD: example
            PGDATABASE: my_db
            PGHOST: postgresql
            PGPORT: 5432
    postgresql:
        container_name: postgresql
        image: postgres:14.1-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: my_db
        volumes:
            - postgresql-data:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: always
        ports:
            - 8070:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
            - PGADMIN_LISTEN_PORT=80
volumes:
        postgresql-data:
